config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :albums
  resources :artists
  resources :tracks
end

app/models/album.rb
class Album < ApplicationRecord
    has_one_attached :cover_art
    validates :name, :released_at, :kind, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_one_attached :avatar
    validates :name, :formed_at, presence: true
end

app/models/track.rb
class Track < ApplicationRecord
    has_one_attached :audio_file
    validates :name, :length, :album, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :set_album, only:[:edit, :update, :destroy]

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to albums_path, notice: "Updated an album"
    else
      flash[:error] = "Blank field"
      render :edit
    end
  end

  def destroy
    @album.destroy
    redirect_to albums_path
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to albums_path
    else
      flash[:error] = "An error was encountered"
      render :new
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :artist, :released_at, :kind, :cover_art)
  end

  def set_album
    @album = Album.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    before_action :set_artist, only:[:edit, :update, :destroy]

    def index
      @artists = Artist.all
    end
  
    def new
      @artist = Artist.new
    end
  
    def edit
    end
  
    def update
      if @artist.update(artist_params)
        redirect_to artists_path, notice: "Updated an artist"
      else
        flash[:error] = "Blank field"
        render :edit
      end
    end
  
    def destroy
      @artist.destroy
      redirect_to artists_path
    end
  
    def create
      @artist = Artist.new(artist_params)
      
      if @artist.save
        redirect_to artists_path
      else
        flash[:error] = "An error was encountered"
        render :new
      end
    end
  
    private
  
    def artist_params
      params.require(:artist).permit(:name, :formed_at, :bio, :avatar)
    end
  
    def set_artist
      @artist = Artist.find(params[:id])
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    before_action :set_track, only:[:edit, :update, :destroy]

    def index
      @tracks = Track.all
    end
  
    def new
      @track = Track.new
    end
  
    def edit
    end
  
    def update
      if @track.update(track_params)
        redirect_to tracks_path, notice: "Updated an track"
      else
        flash[:error] = "Blank field"
        render :edit
      end
    end
  
    def destroy
      @track.destroy
      redirect_to tracks_path
    end
  
    def create
      @track = Track.new(track_params)
      
      if @track.save
        redirect_to tracks_path
      else
        flash[:error] = "An error was encountered"
        render :new
      end
    end
  
    private
  
    def track_params
      params.require(:track).permit(:name, :length, :audio_file, :artist, :album, :credits)
    end
  
    def set_track
      @track = Track.find(params[:id])
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/albums/_form.html.haml
.form-container
  = form_with model: @album do |f|
    .text-field.field-container
      = f.label :name
      = f.text_field :name
    %br
    .text-field.field-container
      = f.label :artist
      = f.text_field :artist
    %br
    .radio-field.field-container
      = f.label :kind, 'Type of album:'
      .radio-option
        = f.radio_button :kind, 'LP'
        = f.label :kind_lp, "LP"
      .radio-option
        = f.radio_button :kind, 'EP'
        = f.label :kind_ep, "EP"
      .radio-option
        = f.radio_button :kind, 'Single'
        = f.label :kind_single, "Single"
      %br
      .date-field.field-container
      = f.label :released_at, 'Release:'
      = f.date_field :released_at
      %br
      %br
    .file-field.field-container
      =f.label :cover_art
      =f.file_field :cover_art
      %br
      %br

    .submit-field.field-container
      = f.submit 'Add album'
    %br
    %br
  .back-field.field-container
    = link_to 'Back to albums', albums_path

app/views/albums/edit.html.haml
.form-container
  %h1 Edit album

  = render 'form'

app/views/albums/index.html.haml
.top-div
  .page-header
    %h1 Welcome to your library.
    %p Here are your favorite albums.

  .search-bar
    = form_tag method: :get, role: "search" do
      %p
        = text_field_tag :search, params[:search], class: "search-control", placeholder: "Search for album.."
  .ext-links
    = link_to artists_path do
      See artists
    = "&nbsp".html_safe
    = "&nbsp".html_safe
    = "&nbsp".html_safe
    = link_to tracks_path do
      See tracks

.second-div
  .btn-add
    = link_to "Add an album", new_album_path
  %br
  %br

  .table
    %table
      %thead
        %tr
          %th 
          %th Album
          %th Artist
          %th Type
          %th Year
          %th
      %tbody
        - @albums.each do |album|
          %tr
            %td
              - if album.cover_art.attached?
                = image_tag album.cover_art.variant(resize:"50x50")
              - else
                = image_tag "album-def.png", size:"50x50"
            %td
              = album.name
            %td
              = album.artist
            %td
              = album.kind
            %td
              = album.released_at.year
            %td
              = link_to edit_album_path(album.id) do
                Edit
              = "&nbsp".html_safe
              = link_to album_path(album.id), method: :delete, data: { confirm: "Delete album?"} do
                Delete
  
  

app/views/albums/new.html.haml
.form-container
  %h1 Add an Album

  = render 'form'

app/views/artists/_form.html.haml
.form-container
  = form_with model: @artist do |f|
    .text-field.field-container
      = f.label :name
      = f.text_field :name
    %br
    .text-field.field-container
      = f.label :bio
      = f.text_area :bio
    %br

    .file-field.field-container
      =f.label :avatar
      =f.file_field :avatar
      %br
      %br

    .date-field.field-container
      = f.label :formed_at, 'Formed:'
      = f.date_field :formed_at

    .submit-field.field-container
      = f.submit 'Add artist'
    %br
    %br
    
  .back-field.field-container
    = link_to 'Back to artists', artists_path

app/views/artists/edit.html.haml
.form-container
  %h1 Edit artist

  = render 'form'

app/views/artists/index.html.haml
.top-div
  .page-header
    %h1 Welcome to your library.
    %p Here are your favorite artists.

  .search-bar
    = form_tag method: :get, role: "search" do
      %p
        = text_field_tag :search, params[:search], class: "search-control", placeholder: "Search for artist.."
  .ext-links
    = link_to albums_path do
      See albums
    = "&nbsp".html_safe
    = "&nbsp".html_safe
    = "&nbsp".html_safe
    = link_to tracks_path do
      See tracks

.second-div
  .btn-add
    = link_to "Add an artist", new_artist_path
  %br
  %br

  .table
    %table
      %thead
        %tr
          %th
          %th Artist
          %th Bio
          %th Formed
          %th
      %tbody
        - @artists.each do |artist|
          %tr
            %td
              - if artist.avatar.attached?
                = image_tag artist.avatar.variant(resize:"50x50")
              - else
                = image_tag "artist-def.jpg", size:"50x50"
            %td
              = artist.name
            %td
              = artist.bio
            %td
              = artist.formed_at.year
            %td
              = link_to edit_artist_path(artist.id) do
                Edit
              = "&nbsp".html_safe
              = link_to artist_path(artist.id), method: :delete, data: { confirm: "Delete artist?"} do
                Delete
  
  

app/views/artists/new.html.haml
.form-container
  %h1 Add a new artist

  = render 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMusiclib</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tracks/_form.html.haml
.form-container
  = form_with model: @track do |f|
    .text-field.field-container
      = f.label :name
      = f.text_field :name
    %br
    .text-field.field-container
      = f.label :artist
      = f.text_field :artist
    %br
    .text-field.field-container
      = f.label :album
      = f.text_field :album
    %br
    .text-field.field-container
      = f.label :length
      = f.text_field :length
      %br
      %br
    .file-field.field-container
      =f.label :track
      =f.file_field :url
      %br
      %br

    .submit-field.field-container
      = f.submit 'Add track'
    %br
    %br
  .back-field.field-container
    = link_to 'Back to tracks', tracks_path

app/views/tracks/edit.html.haml
.form-container
  %h1 Edit track

  = render 'form'

app/views/tracks/index.html.haml
.top-div
  .page-header
    %h1 Welcome to your library.
    %p Here are your favorite tracks.

  .search-bar
    = form_tag method: :get, role: "search" do
      %p
        = text_field_tag :search, params[:search], class: "search-control", placeholder: "Search for track.."
  .ext-links
    = link_to artists_path do
      See artists
    = "&nbsp".html_safe
    = "&nbsp".html_safe
    = "&nbsp".html_safe
    = link_to albums_path do
      See albums

.second-div
  .btn-add
    = link_to "Add a track", new_track_path
  %br
  %br

  .table
    %table
      %thead
        %tr
          %th
          %th Track
          %th Artist
          %th Album
          %th Length
          %th
      %tbody
        - @tracks.each do |track|
          %tr
            %td
              - if track.audio_file.attached?
                = track_tag track.audio_file
            %td
              = track.name
            %td
              = track.artist
            %td
              = track.album
            %td
              = track.length
            %td
              = link_to edit_track_path(track.id) do
                Edit
              = "&nbsp".html_safe
              = link_to track_path(track.id), method: :delete, data: { confirm: "Delete track?"} do
                Delete
  
  

app/views/tracks/new.html.haml
.form-container
  %h1 Add a new track

  = render 'form'